require '../tools/readJSON'
require '../tools/csv2json'
require '../tools/excel2csv'
require 'csv'
require 'json'
require 'time'
require "json-diff"
require "hashdiff"
require 'yomu'

curren_dir = File.dirname(__FILE__)

puts "current directory: #{curren_dir}"

@converted_json_dir = "#{curren_dir}/../converted_json/"

@dt4_formula_json = "dt4_seed_data_formula.json"

#02
def insert_document_workflow_status(seedTrialID)
     @seed_json_data = read_json_from_dir(@converted_json_dir, @dt4_formula_json)
     @seed_data = @seed_json_data.find {|x| x['seedTrialID'] == "#{seedTrialID}"}
     puts @seed_data
sql_insert_document_workflow_status =
    "
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws1_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws1_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws1_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws1_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws1_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws1_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws2_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws2_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws2_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws2_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws2_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws2_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws3_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws3_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws3_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws3_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws3_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws3_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws4_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws4_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws4_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws4_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws4_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws4_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws5_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws5_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws5_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws5_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws5_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws5_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws6_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws6_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws6_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws6_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws6_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws6_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws7_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws7_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws7_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws7_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws7_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws7_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws8_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws8_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws8_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws8_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws8_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws8_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
      INSERT INTO document_workflow_status (identifier,status_code,comment_text,status_date_range_low,study_protocol_identifier,date_last_created,date_last_updated,status_date_range_high,user_last_created_id,user_last_updated_id,current,previous) VALUES ('#{@seed_data['dws9_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_status_code'].gsub("'", ""){ |m| m == "'" ? m : "" }}', #{@seed_data['dws9_comment_text'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws9_status_date_range_low'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_study_protocol_identifier'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_date_last_created'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_date_last_updated'].gsub("'", "") { |m| m == "'" ? m : "" }}', #{@seed_data['dws9_status_date_range_high'].gsub("'", "") { |m| m == "'" ? m : "" }},'#{@seed_data['dws9_user_last_created_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_user_last_updated_id'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_current'].gsub("'", "") { |m| m == "'" ? m : "" }}','#{@seed_data['dws9_previous'].gsub("'", "") { |m| m == "'" ? m : "" }}');
     "
     puts sql_insert_document_workflow_status
end

insert_document_workflow_status 'ST20182602A'