require '../tools/readJSON'
require '../tools/csv2json'
require '../tools/excel2csv'
require 'csv'
require 'json'
require 'time'
require "json-diff"
require "hashdiff"
require 'yomu'

curren_dir = File.dirname(__FILE__)

puts "current directory: #{curren_dir}"

@converted_json_dir = "#{curren_dir}/../converted_json/"

@dt4_formula_json = "dt4_seed_data_formula.json"


#03
def insert_planned_activity(seedTrialID)
     @seed_json_data = read_json_from_dir(@converted_json_dir, @dt4_formula_json)
     @seed_data = @seed_json_data.find {|x| x['seedTrialID'] == "#{seedTrialID}"}
     puts @seed_data
sql_insert_planned_activity =
    "
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-165}',#{@seed_data['pactiv1_category_code']},#{@seed_data['pactiv1_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_study_protocol_identifier']},#{@seed_data['pactiv1_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_date_last_updated']},#{@seed_data['pactiv1_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv1_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-164}',#{@seed_data['pactiv2_category_code']},#{@seed_data['pactiv2_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_study_protocol_identifier']},#{@seed_data['pactiv2_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_date_last_updated']},#{@seed_data['pactiv2_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv2_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-163}',#{@seed_data['pactiv3_category_code']},#{@seed_data['pactiv3_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_text_description']},#{@seed_data['pactiv3_study_protocol_identifier']},#{@seed_data['pactiv3_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_date_last_updated']},#{@seed_data['pactiv3_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv3_display_order']});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-162}',#{@seed_data['pactiv4_category_code']},#{@seed_data['pactiv4_subcategory_code']},#{@seed_data['pactiv4_lead_product_indicator']},#{@seed_data['pactiv4_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv4_study_protocol_identifier']},#{@seed_data['pactiv4_intervention_identifier']},#{@seed_data['pactiv4_date_last_created']},#{@seed_data['pactiv4_date_last_updated']},#{@seed_data['pactiv4_user_last_created_id']},#{@seed_data['pactiv4_user_last_updated_id']},#{@seed_data['pactiv4_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-161}',#{@seed_data['pactiv5_category_code']},#{@seed_data['pactiv5_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_study_protocol_identifier']},#{@seed_data['pactiv5_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_date_last_updated']},#{@seed_data['pactiv5_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv5_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-160}',#{@seed_data['pactiv6_category_code']},#{@seed_data['pactiv6_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_study_protocol_identifier']},#{@seed_data['pactiv6_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_date_last_updated']},#{@seed_data['pactiv6_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv6_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-159}',#{@seed_data['pactiv7_category_code']},#{@seed_data['pactiv7_subcategory_code'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_lead_product_indicator'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_text_description']},#{@seed_data['pactiv7_study_protocol_identifier']},#{@seed_data['pactiv7_intervention_identifier'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_date_last_created'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_date_last_updated']},#{@seed_data['pactiv7_user_last_created_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_user_last_updated_id'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv7_display_order']});
      INSERT INTO planned_activity (identifier,category_code,subcategory_code,lead_product_indicator,text_description,study_protocol_identifier,intervention_identifier,date_last_created,date_last_updated,user_last_created_id,user_last_updated_id,display_order) VALUES ('#{@seed_data['study_milestone_identifier'].gsub("'", "").to_i-158}',#{@seed_data['pactiv8_category_code']},#{@seed_data['pactiv8_subcategory_code']},#{@seed_data['pactiv8_lead_product_indicator']},#{@seed_data['pactiv8_text_description'].gsub("'", ""){ |m| m == "'" ? m : "" }},#{@seed_data['pactiv8_study_protocol_identifier']},#{@seed_data['pactiv8_intervention_identifier']},#{@seed_data['pactiv8_date_last_created']},#{@seed_data['pactiv8_date_last_updated']},#{@seed_data['pactiv8_user_last_created_id']},#{@seed_data['pactiv8_user_last_updated_id']},#{@seed_data['pactiv8_display_order'].gsub("'", ""){ |m| m == "'" ? m : "" }});
     "
     puts sql_insert_planned_activity
end

# insert_planned_activity 'ST20182602A'
